#+OPTIONS: html-link-use-abs-url:nil html-postamble:auto
#+OPTIONS: html-preamble:t html-scripts:t html-style:t html5-fancy:nil
#+OPTIONS: tex:t
#+CREATOR: <a href="http://www.gnu.org/software/emacs/">Emacs</a> 24.4.1 (<a href="http://orgmode.org">Org</a> mode 8.0)
#+HTML_CONTAINER: div
#+HTML_DOCTYPE: xhtml-strict
#+HTML_HEAD:
#+HTML_HEAD_EXTRA:
#+HTML_LINK_HOME:
#+HTML_LINK_UP:
#+HTML_MATHJAX:
#+INFOJS_OPT:
#+LATEX_HEADER:
#+TITLE: fun with clojure+overtone

* first steps

  1. make sure you have =Emacs 24.3= or above and =git=
  2. rename your current emacs config files (=~/.emacs=, =~/.emacs.d= to
     something else)
  2. git clone https://github.com/overtone/emacs-live to your home
     directory

     it is possible to run overtone in your own environment, but
     =emacs-live= saves you a lot of trouble. however, it is also a
     highly opinionated starter kit and comes with a bunch of
     pre-cusomizations.  to add your own and play nice with the
     emacs-live defaults, follow the instructions at

     http://overtone.github.io/emacs-live/doc-customisation.html

     here's a quick example following the cusomization instructions,
     to add some custom modules.

** example: adding =elscreen= and =git-timemachine=

   #+BEGIN_SRC sh :eval never
   cp -R ~/emacs-live/packs/template ~/emacs-live-packs
   mv ~/emacs-live-packs/{user-template-pack,my-custom-pack}
   #+END_SRC

   create the file =~/.emacs-live.el= and in it, add

   #+BEGIN_SRC emacs-list :eval never
   (live-append-packs '(~/emacs-live-packs/my-custom-pack))
   #+END_SRC

   so now our pack gets loaded on startup. I'm going to skip the pack
   stuff and just pull =use-package= and pull the 2 packages I
   want. /This is probably not what the =emacs-live= folks will
   recommend doing./

*** =init.el=

    #+BEGIN_SRC emacs-lisp :eval never :file ~/emacs-live-packs/my-custom-pack/init.el
      ;; User pack init file
      ;;
      ;; Use this file to initiate the pack configuration.
      ;; See README for more information.

      ;; Load bindings config
      (live-load-config-file "bindings.el")

      (require 'package)
      (add-to-list 'package-archives
                   '("marmalade" . "http://marmalade-repo.org/packages/") t)
      (add-to-list 'package-archives
                   '("melpa" . "http://melpa.milkbox.net/packages/"))
      (add-to-list 'package-archives
                   '("gnu" . "http://elpa.gnu.org/packages/"))
      (package-initialize)

      ;; http://stackoverflow.com/questions/21064916/auto-install-emacs-packages-with-melpa
      (if (not (package-installed-p 'use-package))
          (progn
            (package-refresh-contents)
            (package-install 'use-package)))

      (require 'use-package)

      (use-package elscreen :ensure elscreen)
      (use-package git-timemachine :ensure git-timemachine)

    #+END_SRC

    launch emacs; if all goes well, you should have a working
    =emacs-live= install with =elscreen= and =git-timemachine=. OK, on
    to overtone.

* starting our overtone project

  Presumably you have =clojure= and =leiningen= working already...

  #+BEGIN_SRC sh :eval never
  lein new ohack
  #+END_SRC

  within =ohack=, update the dependencies in [[file:ohack/project.clj=]],
  and open [[file:ohack/src/ohack/core.clj]]
